namespace VisualRelay.Core.Init;

// NONE (106) — never decides the strategy: markup, style, data, query, template,
// shader and build languages, plus the ones where automated tests are rare. A
// repository made only of these still gets the separate-file strategy, so several
// rows keep real test path conventions worth feeding the classifier later.
//
// Three alias rows of the source list are merged here: glsl-es into glsl, latex
// into tex (whose .ins marker it contributes) and terraform-module into hcl
// (whose versions.tf marker it contributes). jscript is dropped outright, since
// its only signal was the .js extension that belongs to javascript.
//
// Extensions a mainstream language also claims are gone from the weaker row:
// .sql stays with sql, so pl-sql keeps its package files and transact-sql only
// its project file; .r stays with r, .bas with basic, .cl with opencl, .csh with
// c-shell, .st with smalltalk, .m with objective-c, .prg with foxpro, .yml and
// .yaml with yaml, .tf with hcl, .tex with tex and .cls with apex. That leaves
// four rows with no extension of their own and one, xbase-pp, with none at all.
public static partial class TestLayoutCatalog
{
    private static readonly TestLayoutLanguage[] NoneRows =
    [
        new("sql", TestLayoutBucket.None, [".sql"], [], ["tests/*.sql"]),
        new("scratch", TestLayoutBucket.None, [".sb3"], [], []),
        new("assembly", TestLayoutBucket.None, [".s", ".asm"], [], ["test/", "*_test.s"]),
        new("cobol", TestLayoutBucket.None, [".cbl", ".cob"], [], ["tests/", "*.cut"]),
        new("sas", TestLayoutBucket.None, [".sas"], [], ["tests/"]),
        new("classic-visual-basic", TestLayoutBucket.None, [".frm", ".vbp"], [], []),
        new("pl-sql", TestLayoutBucket.None, [".pks", ".pkb"], [], ["tests/", "test_*.pkb"]),
        new("transact-sql", TestLayoutBucket.None, [], ["*.sqlproj"], ["tests/"]),
        new("vbscript", TestLayoutBucket.None, [".vbs"], [], []),
        new("labview", TestLayoutBucket.None, [".vi", ".lvproj"], [], []),
        new("ladder-logic", TestLayoutBucket.None, [".l5x"], [], []),
        new("vhdl", TestLayoutBucket.None, [".vhd", ".vhdl"], [], ["tb/", "testbench/", "*_tb.vhd", "test/"]),
        new("xslt", TestLayoutBucket.None, [".xsl", ".xslt"], [], ["test/", "*.xspec"]),
        new("foxpro", TestLayoutBucket.None, [".prg", ".scx"], [], []),
        new("applescript", TestLayoutBucket.None, [".applescript", ".scpt"], [], []),
        new("awk", TestLayoutBucket.None, [".awk"], [], ["test/", "*.ok"]),
        new("bc", TestLayoutBucket.None, [".bc"], [], []),
        new("bcpl", TestLayoutBucket.None, [".b"], [], []),
        new("c-shell", TestLayoutBucket.None, [".csh"], [], []),
        new("cl-os-400", TestLayoutBucket.None, [".clle"], [], []),
        new("ct", TestLayoutBucket.None, [], [], []),
        new("egl", TestLayoutBucket.None, [".egl"], [], []),
        new("gams", TestLayoutBucket.None, [".gms"], [], []),
        new("gml", TestLayoutBucket.None, [".gml"], ["*.yyp"], []),
        new("io", TestLayoutBucket.None, [".io"], [], ["tests/"]),
        new("j", TestLayoutBucket.None, [".ijs"], [], []),
        new("jsharp", TestLayoutBucket.None, [".jsl"], [], []),
        new("logo", TestLayoutBucket.None, [".lgo"], [], []),
        new("ms-dos-batch", TestLayoutBucket.None, [".bat", ".cmd"], [], []),
        new("netlogo", TestLayoutBucket.None, [".nlogo"], [], []),
        new("opencl", TestLayoutBucket.None, [".cl"], [], ["test/"]),
        new("pl-i", TestLayoutBucket.None, [".pli"], [], []),
        new("powerscript", TestLayoutBucket.None, [".srw", ".pbl"], [], []),
        new("pure-data", TestLayoutBucket.None, [".pd"], [], []),
        new("purebasic", TestLayoutBucket.None, [".pb", ".pbi"], [], []),
        new("q", TestLayoutBucket.None, [".q"], [], ["tests/"]),
        new("rebol", TestLayoutBucket.None, [".reb"], [], ["tests/"]),
        new("ring", TestLayoutBucket.None, [".ring"], [], ["tests/"]),
        new("structured-text", TestLayoutBucket.None, [".exp"], [], []),
        new("tcsh", TestLayoutBucket.None, [".tcsh"], [], []),
        new("thinbasic", TestLayoutBucket.None, [".tbasic"], [], []),
        new("xbase-pp", TestLayoutBucket.None, [], [], []),
        new("xc", TestLayoutBucket.None, [".xc"], [], []),
        new("xojo", TestLayoutBucket.None, [], [], []),
        new("xpl", TestLayoutBucket.None, [".xpl"], [], []),
        new("z-shell", TestLayoutBucket.None, [".zsh"], [], ["tests/", "*.zunit"]),
        new("html", TestLayoutBucket.None, [".html"], ["index.html"], ["tests/", "e2e/", "cypress/e2e/", "*.spec.ts"]),
        new("css", TestLayoutBucket.None, [".css"], [], ["tests/", "e2e/"]),
        new("xml", TestLayoutBucket.None, [".xml"], [], []),
        new("markdown", TestLayoutBucket.None, [".md"], [], []),
        new("sass", TestLayoutBucket.None, [".sass"], [], ["test/"]),
        new("scss", TestLayoutBucket.None, [".scss"], [], ["test/*.scss"]),
        new("less", TestLayoutBucket.None, [".less"], [], []),
        new("stylus", TestLayoutBucket.None, [".styl"], [], []),
        new("glsl", TestLayoutBucket.None, [".glsl", ".vert", ".frag"], [], ["tests/"]),
        new("hlsl", TestLayoutBucket.None, [".hlsl", ".fx"], [], ["tests/"]),
        new("wgsl", TestLayoutBucket.None, [".wgsl"], [], ["tests/"]),
        new("metal", TestLayoutBucket.None, [".metal"], [], ["Tests/"]),
        new("verilog", TestLayoutBucket.None, [".v", ".vh"], [], ["tb/", "*_tb.v", "test/"]),
        new("systemverilog", TestLayoutBucket.None, [".sv", ".svh"], [], ["tb/", "*_tb.sv", "*_unit_test.sv"]),
        new("graphql", TestLayoutBucket.None, [".graphql", ".gql"], [], []),
        new("sparql", TestLayoutBucket.None, [".rq", ".sparql"], [], ["tests/"]),
        new("cypher", TestLayoutBucket.None, [".cypher", ".cql"], [], []),
        new("promql", TestLayoutBucket.None, [], [], ["tests/*.yml"]),
        new("kql", TestLayoutBucket.None, [".kql", ".csl"], [], []),
        new("dax", TestLayoutBucket.None, [], [], []),
        new("power-query-m", TestLayoutBucket.None, [".pq"], [], ["*.query.pq"]),
        new("mdx", TestLayoutBucket.None, [".mdx"], [], []),
        new("datalog", TestLayoutBucket.None, [".dl"], [], ["tests/"]),
        new("hcl", TestLayoutBucket.None, [".tf", ".hcl"], [".terraform.lock.hcl", "versions.tf"], ["tests/*.tftest.hcl", "test/*_test.go", "examples/"]),
        new("nix", TestLayoutBucket.None, [".nix"], ["flake.nix", "default.nix", "shell.nix"], ["tests/", "nixos/tests/*.nix"]),
        new("bicep", TestLayoutBucket.None, [".bicep"], ["bicepconfig.json"], ["tests/*.bicep", "*.tests.bicep"]),
        new("cue", TestLayoutBucket.None, [".cue"], [], ["*_test.cue"]),
        new("dhall", TestLayoutBucket.None, [".dhall"], [], ["*Test.dhall"]),
        new("jsonnet", TestLayoutBucket.None, [".jsonnet", ".libsonnet"], ["jsonnetfile.json"], ["tests/", "*_test.jsonnet"]),
        new("yaml", TestLayoutBucket.None, [".yml", ".yaml"], [], []),
        new("json", TestLayoutBucket.None, [".json"], [], []),
        new("toml", TestLayoutBucket.None, [".toml"], [], []),
        new("make", TestLayoutBucket.None, [".mk"], ["GNUmakefile"], []),
        new("cmake", TestLayoutBucket.None, [".cmake"], [], ["Tests/"]),
        new("starlark", TestLayoutBucket.None, [".bzl", ".star"], ["WORKSPACE", "MODULE.bazel", "BUILD.bazel"], ["tests/", "*_test.bzl", "*_tests.bzl"]),
        new("apl", TestLayoutBucket.None, [".apl", ".dyalog"], [], ["tests/"]),
        new("basic", TestLayoutBucket.None, [".bas"], [], []),
        new("forth", TestLayoutBucket.None, [".fth", ".4th"], [], ["test/", "*-test.fth"]),
        new("fish-shell", TestLayoutBucket.None, [".fish"], [], ["tests/*.fish"]),
        new("nushell", TestLayoutBucket.None, [".nu"], [], ["tests/"]),
        new("openscad", TestLayoutBucket.None, [".scad"], [], ["tests/"]),
        new("wat", TestLayoutBucket.None, [".wat", ".wast"], [], ["test/*.wast"]),
        new("protocol-buffers", TestLayoutBucket.None, [".proto"], ["buf.yaml", "buf.gen.yaml"], []),
        new("thrift", TestLayoutBucket.None, [".thrift"], [], []),
        new("razor", TestLayoutBucket.None, [".cshtml", ".razor"], [], ["*Tests.cs"]),
        new("jinja", TestLayoutBucket.None, [".j2", ".jinja"], [], []),
        new("liquid", TestLayoutBucket.None, [".liquid"], [], ["test/"]),
        new("handlebars", TestLayoutBucket.None, [".hbs"], [], []),
        new("mustache", TestLayoutBucket.None, [".mustache"], [], []),
        new("freemarker", TestLayoutBucket.None, [".ftl"], [], ["*Test.java"]),
        new("apache-velocity", TestLayoutBucket.None, [".vm"], [], ["*Test.java"]),
        new("erb", TestLayoutBucket.None, [".erb"], [], ["spec/"]),
        new("twig", TestLayoutBucket.None, [".twig"], [], ["tests/*Test.php"]),
        new("pug", TestLayoutBucket.None, [".pug"], [], []),
        new("haml", TestLayoutBucket.None, [".haml"], [], ["spec/"]),
        new("tex", TestLayoutBucket.None, [".tex", ".sty"], ["latexmkrc", "build.lua", "*.ins"], ["testfiles/*.lvt", "*.tlg"]),
        new("ansible", TestLayoutBucket.None, [], ["ansible.cfg", "galaxy.yml"], ["molecule/*/converge.yml", "molecule/*/verify.yml", "roles/*/tests/", "tests/"]),
        new("dockerfile", TestLayoutBucket.None, [".dockerfile"], ["Dockerfile", "compose.yaml"], ["tests/"]),
        new("jupyter-notebook", TestLayoutBucket.None, [".ipynb"], [], ["tests/test_*.py"]),
        new("dbt", TestLayoutBucket.None, [], ["dbt_project.yml", "profiles.yml"], ["tests/*.sql", "models/**/schema.yml"]),
    ];
}
